version: "3.9"
services:
  flask:
    build:
      context: ..
      dockerfile: ./docker/dockerfile
      args:
        FLASK_PORT: ${FLASK_PORT}
    image: flask:latest
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - HOST=${HOST}
      - FLASK_PORT=${FLASK_PORT}
      - DEVELOPMENT=${DEVELOPMENT}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SYNC=${SYNC}
  mysql:
    image: mysql:8.0-debian
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
