FROM python:3.12-alpine

ARG PORT=8080
ENV PORT=$PORT

WORKDIR /backend

COPY . .

RUN pip install --no-cache-dir -r requirements.txt
RUN chmod +x ./docker/scripts/wait-for-db.sh

EXPOSE ${PORT}

ENTRYPOINT ["./docker/scripts/wait-for-db.sh"]

CMD ["python", "main.py"]
